import { Inter } from "next/font/google";
import { NextAuthProvider } from "next-auth/react";  // Si estás usando NextAuth.js
import MiniKitProvider from "@/components/minikit-provider";
import Link from "next/link"; // Importar Link de Next.js
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <MiniKitProvider>
            {/* Contenido de la página */}
            <div className="flex flex-col min-h-screen">
              {/* Barra de navegación fija en la parte inferior */}
              <nav className="bg-blue-600 text-white p-4 fixed bottom-0 w-full z-10 shadow-lg">
                <div className="flex justify-between items-center container mx-auto px-4">
                  <div className="flex space-x-6">
                    <Link href="/inicio">
                      <a className="hover:text-blue-300 transition duration-300">Inicio</a>
                    </Link>
                    <Link href="/servicios">
                      <a className="hover:text-blue-300 transition duration-300">Servicios</a>
                    </Link>
                    <Link href="/contacto">
                      <a className="hover:text-blue-300 transition duration-300">Contacto</a>
                    </Link>
                  </div>
                </div>
              </nav>

              {/* Aquí se renderiza el contenido de la página */}
              <main className="flex-1">{children}</main>
            </div>
          </MiniKitProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
